### ISSUE TITLE
게시글 등록 시 등록자를 구별할 수 있는 방안 검토

### ISSUE THREAD

**Issue by GentleDot** [bookwhale/bookwhale-server#10]
게시글 등록 시 등록자를 구별할 수 있도록
현재 로그인한 작성자의 identity (ID)로

postIdentity 변수를 추가하면 어떨지 의견드립니다.

검토 부탁드릴께요.

**Comment by highright96** [comment]
**게시글 상세 조회 API** 에 아래와 같은 변수들을 추가했습니다.
확인 부탁드립니다.

**sellerId** - 판매자 ID
**sellerIdentity** - 판매자 아이디
**sellerProfileImage** - 판매자 이미지
**createdDate** -게시글 등록일
**lastModifiedDate** - 게시글 최근 수정일
