### ISSUE TITLE
사용자 정보 조회 api 필요

### ISSUE THREAD

**Issue by YeseopLee** [bookwhale/bookwhale-server#100]
* 사용자 정보를 조회하는 api가 따로 없어서 필요할 것 같습니다. 앱 내에서 따로 닉네임/프로필사진을 사용하니 oauth에서 제공하는걸 그대로 사용할수는 없을것 같아요.

**Comment by highright96** [comment]
@YeseopLee 확인했습니다 오늘 살펴보고 반영할께요

**Comment by GentleDot** [comment]
@highright96 사용자 정보 조회 내용 추가된 Docs 를 notion에 반영해주시고 close 해주시면 될 것 같아요.
