### ISSUE TITLE
[로깅] 애플리케이션 로그를 호스트 디렉토리에 남기기

### ISSUE THREAD

**Issue by highright96** [bookwhale/bookwhale-server#102]
## 작업 내용
* 애플리케이션 로그를 호스트 디렉토리

## 참고 문서
* https://www.baeldung.com/ops/spring-boot-logs-docker
* https://www.hungrydiver.co.kr/bbs/detail/develop?id=64
* https://dev-racoon.tistory.com/m/15

**Comment by GentleDot** [comment]
#109 ~ #112 까지의 반영을 통해 log file이 남겨질 수 있도록 설정하였습니다.

![image](https://user-images.githubusercontent.com/15000594/149678204-f60185de-434e-4377-bcc0-9124cb548c46.png)
