### ISSUE TITLE
[문서] 채팅 서버 문서화

### ISSUE THREAD

**Issue by highright96** [bookwhale/bookwhale-server#108]
* CHAT 서버 API 문서 생성

**Comment by GentleDot** [comment]
- 작업사항
    - [x] 채팅기능 동작, 요청 관련 adoc에 추가 처리 진행
    - [ ] (선택사항) API Docs -> postman에 생성해두기

**Comment by GentleDot** [comment]
postman 작업 제외하겠습니다.
#124 를 통해 반영되어 close 합니다.
