### ISSUE TITLE
게시물 전체조회 로직 관련하여.

### ISSUE THREAD

**Issue by YeseopLee** [bookwhale/bookwhale-server#114]
## 상황
* 현재는 메인화면에서 전체 게시물을 불러온 뒤 사용자가 특정 글들이 찜한 게시글인지 확인하기 위해서는
전체 게시물 조회 -> 내 관심 게시물 조회 -> 순회하며 두 그룹에 중복된 id가 있는지 체크를 해야 합니다. 
필요한건 전체게시물 조회뿐인데 통신을 한번 더 해서 비교하는게 좋은 로직 같지는 않아서 이슈 남깁니다.
전체 게시물 조회할때 favoriteCount만 나오는데, favorite한 사람들의 아이디들을 같이 리턴한다거나 아니면 처음부터 사용자가 좋아요 한 게시물인지 확인할 수 있다거나 등등
다른방법이 있으면 좋을것같은데 어떻게 생각하시나요?

**Comment by highright96** [comment]
관심 게시물 여부를 함께 보내드리는 것이 좋을 것 같네요

**Comment by highright96** [comment]
1. 로그인한 경우
2. 로그인 안한 경우

 delete 시 -> favoriteId 에서 articleId 로 변경

**Comment by highright96** [comment]
상세 조회에서만 관심 등록이 가능하도록 변경

articleId로 관심 삭제 하는 API 추가, 기존에 사용하던 favoriteId로 삭제하는 API는 유지
