### ISSUE TITLE
채팅방 목록 조회 로직 관련

### ISSUE THREAD

**Issue by YeseopLee** [bookwhale/bookwhale-server#123]
## 상황
* 채팅방 목록 조회 api와 각 채팅방 마지막 메시지만을 보여주는 api가 분리되어 있어 각각 호출 후 프론트에서 매핑해주어야 하는 상황.
*  /api/message/{roomId}/last를 채팅방 목록에서 마지막 메세지만을 보여주기 위해 사용하고, 마지막 메세지만을 사용하는 다른 용도가 없을것으로 보이므로 처음부터 채팅방 목록을 불러오는 entity안에 포함되어 있는게 더 좋은 코드일거라고 생각하여 이슈 남깁니다. 
* ( + 어차피 비동기처리로 진행하고, 두 response 비교 또한 규모가 크지않기 때문에 성능상의 문제는 크게 없을것이므로 작업 리소스가 비교적 크다면 후순위로 미루고 진행해도 됩니다.)

**Comment by GentleDot** [comment]
실데이터 확인 후 바로 조치하겠습니다.
