### ISSUE TITLE
관심목록 관련 api 수정 요청

### ISSUE THREAD

**Issue by YeseopLee** [bookwhale/bookwhale-server#127]
## 상황
* 현재 관심목록 조회시 리턴값으로 articleId값이 나오는데, 해당 값 대신 favoriteId값을 리턴할 수 있나요?
관심목록추가시에는 articleId를 패러미터로 쓰지만, 삭제시에는 favoriteId를 패러미터로 쓰기 때문에 추가해놓고 삭제하려면 관심목록을 다시 불러와서 순환하면서 favortieId를 따로 찾아야합니다.

* 게시물 상세조회시 내가 관심목록 추가한사항인지는(myFavorite) 나오는데, 동시에 favoriteId도 같이 나오게끔 추가하는 작업이 오래 걸리나요? 일단 관심목록 조회도 같이 불러와서 순환하면서 articleId에 매칭되는 favoriteId를 직접 찾고는 있는데, 비동기로 작업은 되지만 favoriteId조회가 무조건 더 빠른것도 아니고, 가끔 게시물 조회는 완료되었는데, 관심목록조회가 시간이 더 걸려서 게시물 로딩이 덜 되어 로딩이 늘어지는 경우가 있습니다.

**Comment by GentleDot** [comment]
관심목록 조회 시 favoriteId도 같이 조회될 수 있도록 조치할께요.

**Comment by GentleDot** [comment]
```
[ {
  "favoriteId" : 1,
  "articlesResponse" : {
    "articleId" : 1,
    "articleImage" : "이미지",
    "articleTitle" : "책 팝니다~",
    "articlePrice" : "20000원",
    "bookStatus" : "최상",
    "sellingLocation" : "서울",
    "chatCount" : 1,
    "favoriteCount" : 0,
    "beforeTime" : "15분 전"
  }
} ]
```
해당 내용으로 response 되지 않는지 다시 확인 부탁드릴께요.

**Comment by YeseopLee** [comment]
아 1번 상황에 대해서는 제가 문서를 잘못보고 있었네요. 해당부분 확인하였습니다!

**Comment by YeseopLee** [comment]
아 1번을 제가 좀 잘못적었네요.
관심목록 조회시 말고 관심목록 추가시에 현재 articleId만 넘어온다는 문제였습니다!
