### ISSUE TITLE
채팅서버 연결 오류

### ISSUE THREAD

**Issue by YeseopLee** [bookwhale/bookwhale-server#134]
## 버그 사항
* GET http://52.79.148.89:8081/api/message/1?page=0&size=10
 HTTP FAILED: java.net.SocketTimeoutException: failed to connect to /52.79.148.89 (port 8081) from /10.0.2.16 (port 47244) after 5000ms

api문서대로 채팅방은 포트번호 8081로 요청했으나 위와같이 서버가 응답하지 않습니다.

**Comment by GentleDot** [comment]
GET "/api/message/1?page=0&size=10"
요청 시 의도는 아래와 같은데... 한 번 다시 살펴볼께요.
```
MockHttpServletRequest:
      HTTP Method = GET
      Request URI = /api/message/1
       Parameters = {page=[0], size=[10]}
          Headers = []
             Body = null
    Session Attrs = {}

Handler:
             Type = com.bookwhale.message.controller.MessageController
           Method = com.bookwhale.message.controller.MessageController#findMessages(Long, Pagination)

Async:
    Async started = false
     Async result = null

Resolved Exception:
             Type = null

ModelAndView:
        View name = null
             View = null
            Model = null

FlashMap:
       Attributes = null

MockHttpServletResponse:
           Status = 200
    Error message = null
          Headers = [Content-Type:"application/json;charset=UTF-8"]
     Content type = application/json;charset=UTF-8
             Body = [{"senderId":1,"senderIdentity":"highright96","content":"안녕하세요.","createdDate":"2022-02-26T18:50:07.846172"}]
    Forwarded URL = null
   Redirected URL = null
          Cookies = []
```

**Comment by GentleDot** [comment]
추가 배포 작업을 생각치 않아서 여러 삽질을 진행했습니.. ㅠㅠ
http://52.79.148.89:8081/ws/info 로 아래 결과를 확인할 수 있고
![image](https://user-images.githubusercontent.com/15000594/155878011-96d71cfc-bee7-4558-8600-3ce5552562c1.png)

다시 요청하시면 빈 배열을 확인하실 수 있습니다.
![image](https://user-images.githubusercontent.com/15000594/155878033-e79cfb78-2af0-47dd-8b47-97eabab4412b.png)
