### ISSUE TITLE
주문 정보(OrderStatus) 에 대한 상태값 확인 요청

### ISSUE THREAD

**Issue by GentleDot** [bookwhale/bookwhale-server#16]
주문정보 화면에서
판매 정보, 구매 정보의 이벤트 설정 시 OrderStatus value에 따라 설정 예정입니다.

value에 대한 정의 확인 부탁드리겠습니다.

**Comment by hose0728** [comment]
총 4가지로 
REQUEST(구매자 요청), ACCEPT(판매자 수락), PURCHASE_CANCEL(구매자 취소), SALE_CANCEL(판매자 취소) 입니다.
