### ISSUE TITLE
채팅방 개설 시 foreground에서도 알림이 올 수 있도록 추가 설정

### ISSUE THREAD

**Issue by GentleDot** [bookwhale/bookwhale-server#166]
https://firebase.google.com/docs/cloud-messaging/concept-options?hl=ko#notification-messages-with-optional-data-payload

포그라운드 상태에서는 data의 값을 읽어들이므로 아래와 같이 message를 구성하도록 변경
```
{
  "message":{
    "token":"bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1...",
    "notification":{
      "title":"Portugal vs. Denmark",
      "body":"great match!"
    },
    "data" : {
      "Nick" : "Mario",
      "Room" : "PortugalVSDenmark"
    }
  }
}
```
- data에 들어갈 값
    - message : 채팅방 개설 안내 (채팅방 제목)
    - roomId : 생성된 채팅방 ID

**Comment by YeseopLee** [comment]
알림을 채팅방 생성시 말고, 그냥 새로운 채팅이 올 때만 알람을 갈 수 있게 하는게 더 좋은방향 같습니다. (채팅방은 개설했으나 대화를 시작하지 않으면 알람 X). 
또, 메세지 알람시에 roomId, 마지막메세지랑 더해 articleTitle도 같이 보내는것도 가능할까요?
덧붙여서 알람을 끄는 기능도 있어야 할 것 같아요.

**Comment by GentleDot** [comment]
dataMap.put("message ", message);
dataMap.put("roomId", roomId.toString());
dataMap.put("senderId", senderId.toString());
dataMap.put("articleTitle", chatRoom.getArticle().getTitle());

4개 추가해볼께요
