### ISSUE TITLE
게시물 삭제 api 요청

### ISSUE THREAD

**Issue by YeseopLee** [bookwhale/bookwhale-server#171]
* 게시물 삭제 api 추가 및 문서화 요청드립니다.

**Comment by GentleDot** [comment]
판매글(게시물) 삭제시 논리 삭제로 처리하도록 변경하고 문서화 할 수 있도록 하겠습니다.

data를 delete 처리는 어려울 것으로 판단되는게 아래 동작에서 article 테이블을 참조하고 있습니다.
- 내 판매글 등록
- 관심글 등록
- 채팅방 생성

논리 삭제로 처리한다면 채팅방 목록 조회는 제외하고 아래 기능에서 삭제된 판매글은 보이지 않도록 재구성해보겠습니다.
- 판매글 목록 조회
- 관심글 목록 조회
- 내 판매글 목록 조회

**Comment by GentleDot** [comment]
판매글 테이블 변경 및 마이그레이션 처리
```
    modify active_yn enum ('Y', 'N') default 'Y' not null comment '판매글 활성 여부 (N인 판매글은 삭제된 판매글)';
```
