### ISSUE TITLE
알림 off에 관한 api 작성 요청드립니다.

### ISSUE THREAD

**Issue by YeseopLee** [bookwhale/bookwhale-server#184]
알림 off 기능을 클라이언트단에서 컨트롤 해보려고 했는데, 현재 구조상 불가능해 보입니다.

FCM의 특정 topic을 구독해서 메세지를 보내는 경우 (전체 공지사항같은)에는 클라이언트에서 구독해지를 시켜줄 수 있지만,
개인 메세지처럼 특정 deviceToken을 타게팅해서 보내는 경우에 클라이언트에서는 off 할 수 없게끔 되어있는것 같습니다.
혹시나 싶어서 아예 앱 시스템설정의 알람 자체를 끄는 식으로 해보려고 했는데, 앱에서 시스템설정의 알람설정에는 접근할 수 없게 되어있네요.

좀 검색해봤더니, 일반적으로 알림 off를 하면 유저 테이블에서 deviceToken을 삭제시키는 식으로 진행한다고 합니다.

해서 deviceToken을 새로 넣고, 삭제시킬 api가 필요할 것 같습니다.

**Comment by GentleDot** [comment]
User 테이블에 pushActivate 컬럼을 추가하여 대응
- [x] pushActivate = "Y" / "N" 추가
- [x] pushActivate 설정 end-point 추가
