### ISSUE TITLE
관심목록 추가 기능 구현

### ISSUE THREAD

**Issue by sunflower8945** [bookwhale/bookwhale-server#20]
- 관심목록 추가 기능 구현 필요
- 중고책 상세페이지에 관심목록 추가 버튼 클릭시 해당 user와 book이 관심(찜)으로 mapping되는 프로세스 필요
- 화면상 표시될 지점 논의 필요 (상세페이지, 메인페이지, 본인의 찜목록 들어가서만 조회되는지 여부..)

**Comment by highright96** [comment]
게시글 상세 조회 API 응답값에 관심 여부 추가

**Comment by highright96** [comment]
완료
