### ISSUE TITLE
Api Docs. 수정 요청 및 궁금한 내용 질문드립니다.

### ISSUE THREAD

**Issue by GentleDot** [bookwhale/bookwhale-server#26]
# 요청내용
1.  1.2 로그인 response 가 `HTTP/1.1 401 Unauthorized` 로 되어 있습니다. 성공 값으로 변경 요청드립니다.
2. 1.6 프로필 업로드 에서  ~request URL의 수정을 요청드립니다. (/api/user/me/profile)~ 
    - PATCH /api/user/profile 로의 변경 확인하였습니다. ^^;

# 확인이 필요한 내용
1. 1.7 프로필 삭제 기능 구현의 경우 현 시점에서 추가 구현이 필요한 사항이라 필요한 기능인지 확인 부탁드릴께요. 
    - 프로필 업로드 기능으로 대체 가능한 내용이 아니라면 추가적으로 삭제 버튼을 넣어보겠습니다.
2. 1.6 프로필 업로드 에서 `profileImage` 가 path로 전달되는지 아니면 이미지 bytecode로 전달되는지 확인 부탁드립니다.
    - URL의 경우 상대경로는 별도로 지정해야 하는지 확인도 부탁드릴께요.

# 기타 (중요하진 않은 내용)
1. 1.5 비밀번호 수정 등에서 기존 비밀번호(oldPassword)를 잘못 입력한 경우 오류의 형식이나 출력 메시지 표기가 가능한지 궁금합니다.
    - "잘못된 비밀번호입니다." 로 응답되고 있어 오류 발생 시 해당 메시지를 그대로 출력하여 구성하였습니다.
    ![image](https://user-images.githubusercontent.com/15000594/134494415-e759d458-83e6-44c9-a4b8-575f52166d61.png)

**Comment by highright96** [comment]
1.2 로그인 response  .. => 여유가 있을 때 고쳐보겠습니다.. 로그인 성공하면 200이 정상적으로 나올거예요! 

1.7 프로필 삭제 기능 ... => 디폴트 이미지로 바꾸기 위한 기능입니다. 삭제가 없으면 디폴트 이미지로 변경이 불가능해서요!

1.6 프로필 업로드 ... => path 로 전달됩니다. 지금은 /main/static/image 에 저장하게 해놨고, 나중에 s3에 저장하려고 합니다. 프론트에서 경로는 신경쓰지 않으셔도 됩니다!

1.5 비밀번호 수정 ... => API가 정상적으로 작동하지 않나요? 현재 비밀번호를 제대로 입력했으면 200을 반환할텐데... 한 번 확인해보겠습니다. 예외 관련 부분은 채팅작업 끝나고 문서에 추가해두겠습니다!

**Comment by GentleDot** [comment]
> 1.2 로그인 response .. => 여유가 있을 때 고쳐보겠습니다.. 로그인 성공하면 200이 정상적으로 나올거예요!
> 
> 1.7 프로필 삭제 기능 ... => 디폴트 이미지로 바꾸기 위한 기능입니다. 삭제가 없으면 디폴트 이미지로 변경이 불가능해서요!
> 
> 1.6 프로필 업로드 ... => path 로 전달됩니다. 지금은 /main/static/image 에 저장하게 해놨고, 나중에 s3에 저장하려고 합니다. 프론트에서 경로는 신경쓰지 않으셔도 됩니다!
> 
> 1.5 비밀번호 수정 ... => API가 정상적으로 작동하지 않나요? 현재 비밀번호를 제대로 입력했으면 200을 반환할텐데... 한 번 확인해보겠습니다. 예외 관련 부분은 채팅작업 끝나고 문서에 추가해두겠습니다!

감사합니다. 
1.5는 동작 잘 되는거 확인했어요.  api 동작 시에 반환되는 오류메시지를 그대로 출력에도 사용한 예제로 전달드린거였습니다. ^^;
해당 이슈는 이미지 삭제도 가능하도록 추가 구현한 뒤에 closing 하겠습니다!

**Comment by highright96** [comment]
넵..! 감사합니다~

**Comment by GentleDot** [comment]
이미지 삭제 처리 구현 완료 - 이슈 처리 완료하여 close 하겠습니다.
![image](https://user-images.githubusercontent.com/15000594/135132383-1a263f64-4da0-464b-8121-3c4413675ec4.png)
