### ISSUE TITLE
게시글 대표 이미지 변경 요청

### ISSUE THREAD

**Issue by highright96** [bookwhale/bookwhale-server#29]
현재 게시글 전체 목록에서 보여주는 **이미지 (대표 이미지) 를 네이버 책 API 에서 제공하는 책 이미지**를 사용하고 있습니다.
네이버 책 API 에서 책 이미지를 제공하지 않는 경우도 있으니, **대표 이미지를 유저가 올린 첫 번째 책 이미지**로 변경하겠습니다

**Comment by highright96** [comment]
**issue/highright96/28,29** 브랜치로 테스트 부탁드립니다.
이미지 업로드도 정상 작동해야합니다.
이상 없으면 close 해주세요!
@GentleDot @sunflower456

**Comment by GentleDot** [comment]
판매글 등록 시 이미지 업로드 최소 1개는 올려야 등록될 수 있도록 보완하였습니다.
@sunflower456  판매글 상세 상에서 보여지는거 확인 후 close 처리해주세요.

![image](https://user-images.githubusercontent.com/15000594/135315956-d770315c-dffd-4552-9d99-9f8ae9e5ea2e.png)

**Comment by highright96** [comment]
판매글 등록 시 이미지 업로드 최소 1개는 올려야 등록될 수 있도록 보완하였습니다

---> 서버 쪽에서 필수 값 처리가 필요합니다.

@highright96 @hose0728

**Comment by highright96** [comment]
완료
