### ISSUE TITLE
내 판매글 조회 기능 확인 요청드립니다.

### ISSUE THREAD

**Issue by GentleDot** [bookwhale/bookwhale-server#30]
2.4 게시글 전체 조회
기능으로 구현하기에는 전체글 조회 후 id로 필터링 하는 개념으로 접근해야 해서 효율적이지 않다고 생각됩니다.

로그인 사용자의 판매글만 조회할 수 있는 기능 요청드립니다.

![image](https://user-images.githubusercontent.com/15000594/134816097-ae210583-b108-4b9c-bb9c-39c7a9d849e6.png)

**Comment by highright96** [comment]
판매글 조회 API를 깜빡했네요. 만들고 말씀 드리겠습니다

**Comment by highright96** [comment]
@GentleDot 
페이징 처리를 위해 필요한 응답값 확인 부탁드립니다. ex) 내 판매글 total count 등...

**Comment by GentleDot** [comment]
@highright96  내 판매글은 sellerId 가 로그인 사용자인 post 리스트 전체를 전달해주시면 됩니다.
별도 페이지 응답값을 설정하지 않고 최초 전체 데이터를 조회하고자 합니다만 추후 보완 시 30일 ~ 90일 이내 목록만 전달받도록 하는걸 생각하고 있습니다.

**Comment by highright96** [comment]
그럼 따로 페이징 처리는 하지 않고 전체 조회하는 API로 만들겠습니다

**Comment by highright96** [comment]
@GentleDot 
수정 완료 했습니다.
**issue/highright96/30,31** 브랜치로 테스트 후 문제 없으면 close 부탁드립니다.

**Comment by GentleDot** [comment]
대상 브런치로 조회 확인하였습니다.
- 추가로 수정해주신 내용도 확인하였습니다.
    1. 사진 변경 (bookThumbnail -> postImage)
    2. postStatus 의 value 변경 (코드 값 -> 상태 명칭)
 
![image](https://user-images.githubusercontent.com/15000594/135492127-41d91de0-7f0b-4105-a60c-967f0e7d331f.png)
