### ISSUE TITLE
관심목록 기능에 대한 검토 내용 건의드립니다.

### ISSUE THREAD

**Issue by GentleDot** [bookwhale/bookwhale-server#31]
1. 관심목록 조회 : postStatus 의 게시글 상태에 대해 enum 명칭(`[SALE, RESERVED, SOLD_OUT]`)을 응답으로 받고 있는데, 이를 `"판매중, 거래중, 판매완료"` 로 변환된 값으로 전달해주실 수 있는지 확인 부탁드릴께요.
    - 우선은 조회 데이터를 각 행으로 출력할 때 코드값을 변환하는 분기처리하여 처리하였습니다.
    ```javascript
    <TableCell align={"center"}>
        {
            /* eslint-disable-next-line no-nested-ternary */
            row.postStatus === "SALE"
                ? "판매중"
                : // eslint-disable-next-line no-nested-ternary
                row.postStatus ===
                  "RESERVED"
                ? "거래중"
                : "판매완료"
        }
    </TableCell>
    ```
![image](https://user-images.githubusercontent.com/15000594/134942757-6a62adf1-bbda-4525-904f-759368c968b0.png)

2. 관심목록 추가 : 로그인한 유저가 동일 postId로 둘 이상의 관심목록으로 등록이 가능한 것으로 확인됩니다.
    - 현재 interestId가 다르면 동일 postId를 등록할 수 있습니다.
    - interestId & postId 결합키로 관심 게시글이 유일 값(unique)으로 가질 수 있도록 검토 요청드립니다.

**Comment by highright96** [comment]
1. 저희 쪽에서 한글로 변환한 후 전달 드릴 수 있습니다! 보통 이런 부분은 프론트에서 처리하나요 아니면 서버에서 처리하나요? 질문입니다!

2. 아하 이 부분 예외 처리를 깜빡했네요. 이번 작업에 추가하겠습니다~

**Comment by GentleDot** [comment]
> 1. 저희 쪽에서 한글로 변환한 후 전달 드릴 수 있습니다! 보통 이런 부분은 프론트에서 처리하나요 아니면 서버에서 처리하나요? 질문입니다!
> 2. 아하 이 부분 예외 처리를 깜빡했네요. 이번 작업에 추가하겠습니다~

1. 에 대한 부분은 
- 화면 상에서는 json 객체로 전달받은 list에서 해당 항목에 대해 접근이 가능할 때 변환 처리가 가능합니다. 
    - 다른 방법이 있는지 모르겠지만, 결국 Json 값으로 List<Object> 를 받아온 상태에서 loop 내에서 변환하고 난 뒤 사용이 가능할 것 같습니다.
        - https://ojava.tistory.com/124
        - https://developer.mozilla.org/ko/docs/Learn/JavaScript/Objects/JSON
    - 위의 코드의 경우에 l테이블 행을 출력하는 loop 안의 코드이기 때문에 변환까지 처리해뒀습니다.
- 서버단에서는 enum에 대해 Attribute converter를 활용하는 방법이 있어요. 참조할만한 링크를 달아둘께요.
    - https://lng1982.tistory.com/279
    - https://techblog.woowahan.com/2600/

**Comment by highright96** [comment]
글을 읽어보니 이 부분은 서버 쪽에서 처리해주는 것이 맞는 것 같네요.
enum에 맞는 상태값을 한글로 보내드리겠습니다!

**Comment by highright96** [comment]
@GentleDot
수정 완료 했습니다.
issue/highright96/30,31 브랜치로 테스트 후 문제 없으면 close 부탁드립니다.

책 상태와 게시글 상태 모두 변환된 값으로 전달하도록 수정했습니다!

**Comment by GentleDot** [comment]
해당 브런치로 조회 확인하였습니다.
api 문서와 달리 response가 조회되는게 확인되는데요.
우선은 전달받는 response value로 조회가 될 수 있도록 조치하겠습니다! api docs 확인 부탁드릴께요.
![image](https://user-images.githubusercontent.com/15000594/135491575-43dc92e8-45b7-469d-86b6-df0c2063e14d.png)

**Comment by GentleDot** [comment]
전달 받은 response로 관심목록 수정 처리하였습니다.
    - 특이사항으로는 로그인한 유저가 생성한 판매글이 관심목록으로 등록이 가능합니다. 수정되는 내용이 아니라면 @sunflower456  판매글 상세 조회에서 로그인 유저의 판매글에도 관심목록 등록이 가능하도록 확인 부탁드리겠습니다.
![image](https://user-images.githubusercontent.com/15000594/135494599-1101a81f-772e-4280-a0d0-56f7fb469bf9.png)

**Comment by highright96** [comment]
**특이사항으로는 로그인한 유저가 생성한 판매글이 관심목록으로 등록이 가능합니다**
--> 넵  딱히 검증을 위한 쿼리를 추가로 날릴 필요가 없다고 생각해서 가능하도록 만들었습니다. 저도 이부분이 애매했는데 당근에서는 가능하더라고요.
