### ISSUE TITLE
채팅 API 추가 요청

### ISSUE THREAD

**Issue by highright96** [bookwhale/bookwhale-server#36]
![image](https://user-images.githubusercontent.com/55661631/136659307-67a1905d-b3b4-4939-b3f6-076a45929158.png)

**Comment by highright96** [comment]
@GentleDot 

**36,37,38 브랜치에서 테스트 해주시면 됩니다!**

**STOMP connection** : /ws

**subscribe** : /sub/chat/room/{roomId}

**send** : /pub/chat/message
{
roomId : 1,
senderId : 1,
senderIdentity : "highright96"
content : "안녕하세요!"
}

궁금한 점은 댓글로 말씀해주세요!

**Comment by GentleDot** [comment]
senderId : 1,
<- 
1. 로그인한 유저의 identity로 이해하면 될까요?
2. 아니면 subscribe 할 때 생성되는 id인가요?

- 로그인 유저의 identity (sequence id)는 어디서 가져올 수 있는지 확인이 필요할 것 같아요.
- 내정보 조회로 가져올 때 사용자 id는 가져오는데 sequence id는 가져오지 않고 있거든요.
--- 
>>> SUBSCRIBE
id:sub-0
destination:/sub/chat/room/1

**Comment by highright96** [comment]
senderId 는 sequence id (pk) 로 생각하시면 됩니다.

내 정보 조회할 때 sequence id (pk) 도 같이 보내도록 수정하겠습니다!

**Comment by GentleDot** [comment]
https://github.com/TeamHerb/Bookstore-Front/pull/28
1차 구현 과정에서
1. 내 정보 조회 시 senderId 추가 확인하였습니다.
    - 해당 값을 활용하여 자신과 상대방 구분, 전송 메시지 출력 양식 구분 등에 활용하였습니다.
2. connect, subscribe, send 기능 동작 확인하였습니다.
    - react node server 동작으로 인해 connection : `http://localhost:9090/ws` 로 설정값을 적용하였습니다.
    - connection이 중첩되는 경우 subscribe가 중첩되어 메시지가 여러개 출력되는 증상을 확인하여 connection이 중첩되지 않도록 설정하였습니다.
3. 기능 구현 확인은 origin/feature/highright96/multi-modules brunch를 pull하여 확인하였습니다.

특이사항 없이 동작 확인하여 해당 이슈는 close 하도록 하겠습니다.
확인 및 수정해주셔서 감사합니다.
