### ISSUE TITLE
3.2 채팅방 목록 조회 응답값 확인 요청드립니다.

### ISSUE THREAD

**Issue by GentleDot** [bookwhale/bookwhale-server#37]
![image](https://user-images.githubusercontent.com/15000594/136658242-c48bb7eb-c40a-48de-940c-6845b82387c6.png)

<!DOCTYPE html>
<html>
<head>
<title></title>

</head>
<body>

POST_ID | CREATED_DATE | LAST_MODIFIED_DATE | BOOK_AUTHOR | BOOK_ISBN | BOOK_LIST_PRICE | BOOK_PUB_DATE | BOOK_PUBLISHER | BOOK_SUMMARY | BOOK_THUMBNAIL | BOOK_TITLE | BOOK_STATUS | DESCRIPTION | POST_STATUS | PRICE | TITLE | SELLER_ID
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2 | 2021-10-09 21:34:08.214108 | 2021-10-09 21:34:08.214108 | 다페이시가즈 | 1158250908 9791158250904 | 13000 | API 미제공 | 브라운힐 | 야채스프의 비밀을 말하고자 하는데 그에 앞서 독자들은 꼭 알아 두어야 할 일이 있다. 그것은 의료를 포함한 우리들의 현대생활 환경은 위험으로 가득 차... 필자는 오랫동안에 걸친 연구 끝에 그 진리에 이르러 야채스프를 개발했다.그리고 야채스프를 중심으로 하고 그것을 보충하는 현미차 등의 이용법을... | https://bookthumb-phinf.pstatic.net/cover/168/919/16891985.jpg?type=m1&udate=20201219 | 야채스프 건강법 (자연의 치유를 체험한 기적의 야채스프) | UPPER | 아아 | SALE | 20000 | 22 | 1

</body>
</html>

## 사용자 "22"가 채팅방을 다음과 같이 요청하여 개설하였을 때
```
{
  "postId" : 2,
  "sellerId" : 1
}
```

GET /api/chat/room  요청으로 
개설자인 "22" 사용자는 채팅방 목록이 조회되나 
sellerId인 "11"은 채팅방 목록을 조회할 수 없는 상태로 확인됩니다.

아래 그림에서 1. SUBSCRIBE 추가한 사용자 ("22") + 상대방인 판매글 등록자 ("11")도 채팅방 목록이 조회될 수 있도록 확인이 필요할 것 같습니다.

확인 부탁드리겠습니다.

![image](https://user-images.githubusercontent.com/15000594/136659474-5c3150e1-e59b-4a88-9b33-1694b9e2561e.png)

**Comment by highright96** [comment]
@GentleDot

**36,37,38 브랜치에서 테스트해 주시면 됩니다!**

**바뀐 파라미터 명이 있으니 Rest Docs 확인 부탁드릴게요!**

아래와 같이 테스트했을 때 정상적으로 작동하는 것을 확인했습니다. 한 번 더 프론트에서 확인 부탁드립니다!

**가정**
유저1이 유저2에게 거래 요청을 하여 채팅방을 개설했을 경우

**테스트**
유저1이 채팅방 목록을 조회했을 때 유저2와의 채팅방이 정상적으로 조회됩니다.
유저2가 채팅방 목록을 조회했을 때 유저1과의 채팅방이 정상적으로 조회됩니다.
유저2가 채팅방을 나갔을 경우 유저1이 채팅방을 조회하면 opponentDelete 가 true로 조회됩니다.
자신이 나간 채팅방은 채팅방 목록을 조회했을 경우 조회되지 않습니다.

**Comment by GentleDot** [comment]
구매자("22") 가 판매글 (postId: 1) 에 채팅 개설 시

채팅목록 조회 확인하였습니다.
![image](https://user-images.githubusercontent.com/15000594/136826741-9ccfe17c-dc4e-4dcd-a277-135f973b842a.png)

- 판매자("11") 확인
- 구매자("22") 확인

**Comment by highright96** [comment]
@GentleDot 

서버쪽에서는 변수명을 제외하고는 변경 사항이 없는데, 화면쪽에서 생긴 문제였었나요?

**Comment by GentleDot** [comment]
> @GentleDot
> 
> 서버쪽에서는 변수명을 제외하고는 변경 사항이 없는데, 화면쪽에서 생긴 문제였었나요?

아뇨, 화면 쪽 변경사항 없었어요. 
아니면 제가 jwt 작성 시 꼬여서 발생된 문제였는지도 모르겠네요. ^^; 실 구현 시에도 문제가 없는지 추가적으로 확인해볼께요.

**Comment by highright96** [comment]
넵! 고생하셨습니다~

**Comment by GentleDot** [comment]
1차 구현 진행하면서 특이사항이 확인되지 않아 해당 이슈는 close 하겠습니다.
