### ISSUE TITLE
채팅방 메시지 - 응답값 확인 요청드립니다. (createdDate)

### ISSUE THREAD

**Issue by GentleDot** [bookwhale/bookwhale-server#42]
![image](https://user-images.githubusercontent.com/15000594/137600800-a8736eb2-315d-4e17-addc-9b60cffbe1a3.png)

아래와 같이 전송 시에 응답값의 createdDate가 null로 확인됩니다.
해당 값의 확인을 부탁드리겠습니다.

```
>>> SEND
destination:/pub/chat/message
content-length:76

{"roomId":6,"senderId":1,"senderIdentity":"11","content":"안녕하세요."}

<<< MESSAGE
destination:/sub/chat/room/6
content-type:application/json
subscription:sub-0
message-id:c3tonxfa-371
content-length:84

{"senderId":1,"senderIdentity":"11","content":"안녕하세요.","createdDate":null}
```

**Comment by highright96** [comment]
mongodb로 교체하면서 해결됐습니다! 

issue/highright96/42,43 에서 확인해주세요!

**Comment by GentleDot** [comment]
![image](https://user-images.githubusercontent.com/15000594/137773174-a80a176f-da5d-436b-85a1-8bd87f38f811.png)

내려오는 채팅 데이터 확인했습니다.
일단 index = 0 이 가장 최근 값으로 나오는 것을 확인하여 

출력할 때는 반대로 뒤집어서 출력하도록 수정하였습니다.
해당 부분은 스크롤 로딩 구현할 때 다시 요청사항이 생기면 말씀드릴께요.

작업 수고많으셨습니다.


![image](https://user-images.githubusercontent.com/15000594/137774566-4dfc9ef0-744d-4a56-8194-80fb90a7f0cc.png)


해당 작업은 
https://github.com/TeamHerb/Bookstore-Front/pull/28
으로 처리될 예정입니다.

**Comment by highright96** [comment]
문제 확인했습니다. 방화벽을 열어둬서 이 코멘트는 삭제해두겠습니다! (혹시 모르니.. ㅎㅎ)
name 에서 teamherb_chat 을 teamherb로 바꾸시면 될 것 같습니다!
