### ISSUE TITLE
Request URI 설정 건의 드립니다. - 채팅 기능 관련

### ISSUE THREAD

**Issue by GentleDot** [bookwhale/bookwhale-server#43]
api의 멀티 모듈 구현에 따라 8080, 9090로 서버 구현이 되어 있는데

/api/chat 으로 시작하는 request 중에는 채팅방 관련 기능과 채팅 기능이 혼재되어 있어 이를 아래와 같이 분리하면 어떤지 건의드립니다.

### 건의 내용
- 8080 에서 요청 받는 기능은 `/api/chat` 으로 시작하는 URI로
    - 3.1 채팅방 생성
    - 3.2 채팅방 목록 조회
    - 3.3 채팅방 삭제

- 9090 에서 요청 받는 기능은 `/api/message` 로 시작하는 URI로
구성하는 방안을 생각해보았습니다.

### 기타사항
- front 측에서 `http-proxy-middleware` 를 활용하여 request의 host(domain)을 다르게 구성함이 가능하여 아래와 같이 대응하였습니다.
    ```
    /*     - 3.4 채팅방의 이전 메세지 조회 기능의 proxy 설정 */
    const { createProxyMiddleware } = require("http-proxy-middleware");

    module.exports = (app) => {
        ...

        app.use(
            // createProxyMiddleware("/api/message", {
            createProxyMiddleware("/api/chat/room/*/messages", {
                target: "http://localhost:9090",
                changeOrigin: true
            })
        );

        ...
    ```
- 해당 변경 내용이 시급한 사안은 아니므로 구현이 번거롭거나 어려운 부분이 있으시다면 pass 해주셔도 무방합니다.

**Comment by highright96** [comment]
**이전 메세지 조회 API** : /api/message/{roomId}?page=0&size=10

**마지막 메세지 조회 API** : /api/message/{roomId}/last

**채팅방 관련 API** : /api/chat/room  -> /api/room 으로 변경했습니다!

issue/highright96/42,43 확인부탁드려요!

**Comment by GentleDot** [comment]
/api/message
/api/room

url 별 multi proxy 구성 완료하였습니다.

issue/highright96/42,43 브런치로 동작 확인했습니다! 수정 감사합니다.
