### ISSUE TITLE
질문$1 : JPA의 entity 동작을 테스트하는 방법에 대해 궁금합니다.

### ISSUE THREAD

**Issue by GentleDot** [bookwhale/bookwhale-server#49]
1. Service 및 Repository context를 확인하는 테스트를 작성하는 부분에 대해 궁금합니다.
    - 테스트용 entity 객체 생성
    - repository 테스트를 작성하려면 core package에 작성하면 될까요?
2. 기존 내용에서 변경되는 경우 작성된 테스트에 대해 수정작업을 진행해도 괜찮을까요?

**Comment by highright96** [comment]
1주차 온라인 회의 때 말씀드렸습니다.
