### ISSUE TITLE
질문$2 : 멀티 모듈로 운영 중인 상태에서 공통으로 사용되는 라이브러리를 추가하려면?

### ISSUE THREAD

**Issue by GentleDot** [bookwhale/bookwhale-server#50]
- Spring Boot Devtools 가 확인되지 않아서 추가를 검토하고자 합니다.
- 해당 라이브러리를 root의 build.gradle에 추가해야하는지 아니면 각 모듈 내 build.gradle에 추가해야하는지 방법이 궁금합니다.
- 관련링크
    - https://velog.io/@bread_dd/Spring-Boot-Devtools

**Comment by highright96** [comment]
1주차 온라인 회의 때 말씀드렸습니다.
