### ISSUE TITLE
[버그] Spring Rest Docs

### ISSUE THREAD

**Issue by highright96** [bookwhale/bookwhale-server#51]
## 필수
1. chat -  Spring Rest Docs 추가 생성 필요

## 선택
1. API - Spring Rest Docs 개선 필요

**Comment by GentleDot** [comment]
#124 를 통해 snipset을 생성할 수 있는 영역은 mvc test로 생성하고 
안되는 영역은 adoc 내 직접 작성하여 보완하였습니다.

- gradle build 시 최상위에서 build를 수행하면 하위 모듈은 알파벳 순서대로 build를 진행하는 것으로 확인됩니다.
    - 의존 관계를 두어 docs 생성 순서를 구성할 수 있을 것 같으나 의존 관계를 두는 것은 권장되지 않는 것으로 보입니다.
    - 참고한 자료 : https://kwonnam.pe.kr/wiki/gradle/multiproject#%EC%9D%98%EC%A1%B4%EC%84%B1_-_%EC%96%B4%EB%8A%90_%EC%9D%98%EC%A1%B4%EC%84%B1%EC%9D%84_%EC%84%A0%ED%83%9D%ED%95%98%EC%A7%80
