### ISSUE TITLE
[수정] Package 관리

### ISSUE THREAD

**Issue by highright96** [bookwhale/bookwhale-server#52]
1. 패키지명 변경
- 기존 : com.teamherb.bookstoreback
- 변경(api) : com.bookwhale.api
- 변경(chat) : com.bookwhale.chat
2. 패키지 분리
- user package에 있는 관심 목록 API를 like package로 분리
  - interest -> like로변경
- user package에 있는 내 판매글 API를 post package로 분리

**주의할 점 : 테스트코드 + Spring Rest Docs 도 변경해야 합니다**

**Comment by GentleDot** [comment]
- package 변경 후 querydsl 객체 생성 시 오류가 발생하는 경우 
build > ~ > `generated 폴더` 내 `Q class`를 제거해야 정상적으로 build 됩니다.

- 관련 링크
  - https://vesselsdiary.tistory.com/146
  - https://kangwoojin.github.io/programing/query-dsl-setting-old/

**Comment by highright96** [comment]
확인했습니다~ 감사합니다!
