### ISSUE TITLE
[판매글] 판매글 목록 조회 API 수정

### ISSUE THREAD

**Issue by highright96** [bookwhale/bookwhale-server#62]
## Task
- [x] 요청
    - [x] 판매지역 추가
    - [x] 판매상태 추가
    => 요청 헝태는 검색 조건, 판매지역, 판매상태가 쿼리 param으로 들어오도록 구성되어야 함.
- [x] 응답
    - [x] 책 제목, 저자, 출판사 제거
    - [x] 판매지역 추가
    - [x] 조회 수 추가
    - [x] 관심 수 추가
    - [x] 유저가 작성한 판매글 설명

**Comment by GentleDot** [comment]
#69 merge 처리로 close 해두겠습니다.
