### ISSUE TITLE
[의견] YAML 파일, Common 모듈 리팩토링

### ISSUE THREAD

**Issue by highright96** [bookwhale/bookwhale-server#65]
1. YAML 파일 정리가 필요한 것 같습니다. 같이 얘기를 나눠봤으면 좋겠습니다!
    * 예시 
    *  auth.yml 분리
    * 개발, 테스트 환경 yml로 분리
2. Common 모듈이 필요한지 의문입니다. 삭제해도 상관없을 것 같은데 어떠신가요?

**Comment by GentleDot** [comment]
1. 크게 구분되게 나뉘면 유지하기 편할 것 같아서 찬성입니다.
2. Common 모듈과 각 api 내 common도 있어 혼동의 여지가 있고 전체 api의 공통기능 구현이 아니면 큰 의미는 없는 것 같아서 의견에 찬성입니다.

**Comment by GentleDot** [comment]
common 모듈에 대해서는 #71 작업에서 api.common으로 이동처리하였습니다.
