### ISSUE TITLE
[버그]게시물 전체조회 오류

### ISSUE THREAD

**Issue by YeseopLee** [bookwhale/bookwhale-server#94]
## 버그 사항
* /api/articles?search=%EC%B1%85%20%EC%A0%9C%EB%AA%A9&page=0&size=10 
* 조회시 search값이 없으면 에러

## 원하는 상황
* serach값이 없으면 조건없이 모든 게시물 조회

**Comment by highright96** [comment]
@YeseopLee 
수정했습니다~ 확인 부탁드려요!

**Comment by YeseopLee** [comment]
확인했습니다! close할게요
