### ISSUE TITLE
[의견]구글 로그인 api 연결

### ISSUE THREAD

**Issue by YeseopLee** [bookwhale/bookwhale-server#95]
## 버그 사항
* 진행했던 구글 로그인 방식이 firebase가 나오면서 deprecated된 방법이라 다른방법으로 진행해야할듯 싶습니다.

## 원하는 상황
* https://console.firebase.google.com
* 위의 링크로 기존의 api 관리하던 계정으로 접속하여 프로젝트 추가 (구글 애널리틱스 필요 x)
* 첨부한 스크린샷의 안드로이드 버튼을 클릭하여 프로젝트 추가 (sha-1값 입력)
* 추가하면 google-services.json 파일 다운로드 가능한데 이걸 전해주세요!
* 추가하고 나면 기존의 구글 api 관리하는 사이트에 신규 추가된 프로젝트를 보면 안드로이드 및 서버용 api들이 자동으로 생성되어있습니다. 이것을 이용하시면 될 것 같습니다.

## 스크린샷

![image](https://user-images.githubusercontent.com/67935576/147865038-c10b0fde-a95c-4d66-8ed0-b9fd262e4b25.png)
![image](https://user-images.githubusercontent.com/67935576/147865078-fcdda4f3-4292-486a-8495-455f83ed6fad.png)

**Comment by GentleDot** [comment]
firebase 생성 완료

**Comment by GentleDot** [comment]
![image](https://user-images.githubusercontent.com/15000594/147865388-1ce483ff-54db-4e38-9afd-22ddfd3ea468.png)
- firebase 프로젝트 연결
    - [x] firebase 내 app 연결 완료
    - [x] json 파일 공유
