### ISSUE TITLE
[버그] 구글 로그인 access token 오류

### ISSUE THREAD

**Issue by YeseopLee** [bookwhale/bookwhale-server#96]
## 버그 사항
* api/oauth/google/login 로 accessToken을 담아 보내면
{"status":500,"message":"서버에 문제가 생겼습니다.","code":"S_001","errors":null} 응답 발생함.

## +의견
* 현재는 구글 로그인 이후 받은 정보를 직접 구글의 https://oauth2.googleapis.com/token 엔드포인트에 보내서 클라이언트로 엑세스토큰을 받은다음 다시 google/login으로 토큰을 담아서 보내고 있는데, 클라이언트단에서 단순히 api를 호출한뒤 그 값만을 서버에게 전달하는게 아니라 api로 받은 정보를 토대로 직접 구글 서버와 통신해서 엑세스토큰에 관한 정보들을 가져와서 다시 전달하는게 좋은(?) 방법인지 모르겠습니다. 일반적인 클라이언트 구글로그인의 경우 엑세스토큰을 직접 반환해주지 않는데에는 이유가 있지않나.. 싶고.. 이전에는 엑세스토큰 받는 과정을 서버에서 했었는데 사실 어떤게 좋은 방법인지 잘 모르겠어서 어떻게 생각하시는지 궁금합니다.

**Comment by GentleDot** [comment]
1. 오류에 대하여
  - accessToken만으로 정보를 조회할 수 없다면 아마도 
      - clientId와 key가 달라 발생하는 문제나 도메인이 유효하지 않게 설정되었기 때문이지 않을까 생각됩니다.
      => 로깅에 대한 정비 후에 원인 확인이 될 것 같습니다. / 괜찮으시다면 요청한 accessToken에 대해 카톡이나 구글문서로 전달해주시면 원인 확인이 용이할 것 같습니다.
      - 설정 상에서 host로 ip 입력이 안되는 상태이고 도메인으로는 https://  입력만 가능하기 때문에 도메인 구성이 고려되지 않는 상태에서는 대응이 어려울 것 같아 다른 로그인 수단의 개발로 진행해야 할 것 같습니다.

2. accessToken으로 요청하는 방식에 대해서
  - 제 생각엔 사용자 정보에 대해 유효한 접근 키로 요청해서 전달받는 방식이어야 HTTP 통신 상으로 정보가 왔다갔다 할 때 token이라는 문자열만 주고받으므로 탈취나 인터셉트 등의 문제를 1차적으로 고려할 수 있는 방식으로 보입니다.
  - 서버에서 accessToken을 요청하려면 사용자로부터 로그인 후 (redirectURL의 host가 일치한 상태에서) 유효한 accessCode를 받아야 요청이 가능한 상태로 확인되므로 webView로 로그인 페이지가 띄워져야 할 것 같은데... 이건 좀 고민해볼 문제 같습니다.

**Comment by YeseopLee** [comment]
일단 AccessToken에 관한 로그는 구글문서에 올려드렸습니다.

**Comment by GentleDot** [comment]
배포 시 https host 도메인이 필요하므로 구글 로그인을 보류하고 카카오 로그인을 추가하는 것으로 보완 예정
(해결된 이슈는 아니므로 close 하지는 않겠습니다.)

**Comment by GentleDot** [comment]
구글 로그인 제외 -> 카카오 로그인으로 대체되어 close 하겠습니다.
